# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adeline Fermanian
email: adeline.fermanian@mines-paristech.fr
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website!
url: https://afermanian.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
twitter_username: AdelineFermani1
github_username: afermanian
minimal_mistakes_skin: dirt
search: false
atom_feed:
  hide: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  # name   : "Adeline Fermanian"
  avatar : "/assets/images/photoprofil.jpg"
  bio    : "I am a postdoctoral researcher interested in theoretical machine learning."
  location : "Paris, France"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:adeline.fermanian[at]mines-paristech[dot]fr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/afermanian"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.co.jp/citations?user=3Mfclk8AAAAJ&hl=en"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/adelinefermanian/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AdelineFermani1"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:adeline.fermanian[at]mines-paristech[dot]fr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/afermanian"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.co.jp/citations?user=3Mfclk8AAAAJ&hl=en"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/adelinefermanian/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AdelineFermani1"

defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/